### ISSUE TITLE
Examples to re-construct Objects from XML

### ISSUE THREAD

**Issue by alete89** [VarianAPIs/Varian-Code-Samples#14]
Hi, thanks for providing examples on this API, they're really helpful.
Though, I'm being unable to read a Patient from it's XML representation. Could you provide an example of de-serialization together with the serialization one that is [here](https://github.com/VarianAPIs/Varian-Code-Samples/wiki/Code-Sample---Patient-XML)

Thanks!
@pabloaberbuj

**Comment by fizxmike** [comment]
Do you wish to simply read the XML data after it's serialized? Is there a compelling reason you want to use c# (a strongly typed language) to do that? 

Or do you want to reconstruct the actual ESAPI objects? (Sorry, this is not possible).

Looks like the way to do it in is to define the deserialization target classes in c# (perhaps these are the definitions you are asking for?):
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/how-to-read-object-data-from-an-xml-file

**Comment by alete89** [comment]
> Or do you want to reconstruct the actual ESAPI objects? (Sorry, this is not possible).

Yes.

> Looks like the way to do it in is to define the deserialization target classes in c# (perhaps these are the definitions you are asking for?)

I actually tried to deserialize a Patient XML into an ESAPI Patient without success.

The final objective was to persist some full patients outside of the network into a development environment so I don't need to query the actual database anymore.
This was the first way that came to my mind. do you suggest another approach?

**Comment by fizxmike** [comment]
The "official" way to do this is with Microsoft Fakes Framework. [Specifically using "shims."](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2017) However, to use Microsoft Fakes Framework requires Visual Studio Enterprise. If your department is serious about software development perhaps they will buy you a license or they already have one.

Surely there are other mocking libraries freely available to C# developers, but I am not familiar with them. Please share what you find!

**Comment by redcurry** [comment]
I wouldn't use the Fakes Frameworks for anything other than unit testing. It seems that you want to store and load patients as a "normal" part of your application (at least during development).

What I would do is not use any ESAPI object in your application. This actually has other benefits in addition to what you want (e.g., unit testing). Instead, create wrappers for the data that you actually need in your application. Because you have control over these wrappers, you can store and load them in any way you want (e.g., XAML, YAML, SQL database). I talk a little about this here: http://www.carlosjanderson.com/use-the-facade-pattern-when-working-with-esapi

During development, you can instantiate these wrappers with your own data. For the release, use ESAPI to fill these wrappers with data. Nothing in your application code needs to change when you switch from development to release. The only change occurs someone at the start of your application, where you choose which class to use to load your patient data (you can even choose this automatically by using the DEBUG constant; see http://www.carlosjanderson.com/use-the-debug-symbol-to-run-debug-code/).
