### ISSUE TITLE
ESAPI logging

### ISSUE THREAD

**Issue by larpra** [VarianAPIs/Varian-Code-Samples#68]
The Eclipse Scripting API 15.5 Reference Guide states the following:

“The system provides logging so that the QA responsible person can always find all plans and structure sets that have been modified by a write-enabled script.”

How can this logging accessed by our IT engineers for troubleshooting API problems?

**Comment by Kiragroh** [comment]
You have to connect to the SQL-Database to access extra tables where this information is stored.
It is not simply accessible with ESAPI alone but you can combine both, like many others did before but you need to have sufficient rights and a designated sql user for this.

**Comment by Kiragroh** [comment]
I have a more practical solution for you. I started to write a log-file for all my clinical scripts.
For instance: if someone opens my planCheck or autoplanning tool a new line is added to a csv-User-Log-file on our server with entrys for time, PC, user, plan-ID etc.

**Comment by Kiragroh** [comment]
In the ESAPI Reference Guide v.16 is a specific example code that should be perfect for you. Should be possible with your version (15.5) too. I cannot try it because I have 15.1 installed:

 static void Execute(Application app)
{
const string MyScript = "MyScript.esapi";
// look for objects created since April 1st 2016 since script was // approved then.
DateTime searchSince = new DateTime(2016, 4, 1);
double searchDays = (DateTime.Now - searchSince).TotalDays;
foreach (PatientSummary summary in app.PatientSummaries)
{
Patient p = app.OpenPatient(summary); // find all plans touched by the script foreach (Course course in p.Courses)
{
          foreach (PlanSetup plan in
              course.PlanSetups.Where
(ps => (DateTime.Now-ps.HistoryDateTime).TotalDays <= searchDays))
{
var scriptLogs = plan.ApplicationScriptLogs; foreach (ApplicationScriptLog log in
scriptLogs.Where(s => s.ScriptFullName == MyScript)) {
Console.WriteLine("Plan \"{0}/{1}/{2}\" touched by " + "script {3} on {4}.",
p.Id, course.Id, plan.Id, log.ScriptFullName, log.HistoryDateTime);
} }
}
// find all structure sets touched by the script foreach (StructureSet structSet in
p.StructureSets.Where
(ss => (DateTime.Now - ss.HistoryDateTime).TotalDays <= searchDays))
{
var scriptLogs = structSet.ApplicationScriptLogs; foreach (ApplicationScriptLog log in
scriptLogs.Where(s => s.ScriptFullName == MyScript)) {
Console.WriteLine("Structure set \"{0}/{1}\" touched by " + "script {2} on {3}.",
                p.Id, structSet.Id,
log.ScriptFullName, log.HistoryDateTime); }
}
        app.ClosePatient();
      }
}
[Eclipse 16.0 Scripting API Reference Guide.pdf](https://github.com/VarianAPIs/Varian-Code-Samples/files/4648185/Eclipse.16.0.Scripting.API.Reference.Guide.pdf)

**Comment by larpra** [comment]
Thanks for the feedback :=). I think we will develop a framework that supplies central logging from all our scripts because this will provide logging i realtime.
